In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/homeprices.csv')

In [ ]:
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [ ]:
model=linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [ ]:
model.coef_

array([135.78767123])

In [ ]:
model.intercept_

180616.43835616432

In [ ]:
model.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

In [ ]:
import pickle

In [ ]:
with open('model_pickle','wb') as file:
  pickle.dump(model,file)

In [ ]:
with open('model_pickle','rb') as file:
  mp=pickle.load(file)

In [ ]:
mp.coef_

array([135.78767123])

In [ ]:
mp.intercept_

180616.43835616432

In [ ]:
mp.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

In [ ]:
import joblib
joblib.dump(model,'model_joblib')

['model_joblib']

In [ ]:
mj=joblib.load('model_joblib')

In [ ]:
mj.coef_

array([135.78767123])

In [ ]:
mj.intercept_

180616.43835616432

In [ ]:
mj.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])